### ISSUE TITLE
call MetaAggregationRouterV2 from other contract

### ISSUE THREAD

**Issue by bakeiro** [KyberNetwork/smart-contracts#1102]
Hi!

I'm starting a project and I plan to call MetaAggregationRouterV2 from another contract, idea it's to call the swap method with the data generated from `api/v1/route/build` question is, is this possible? or has some kind of whitelist or something?

Also, it's always the swap method the main method or I need to check the first bytes of the transaction call to see if other method is called? (`0xe21fd0e` => swap but maybe isn't always `0xe21fd0e`?)

I tried to join the telegram channel but I'm unable to write messages 🙃 any help is welcome!

**Comment by manhlx3006** [comment]
Hi, yes, you can call the MetaAggregationRouterV2 with the data from the build route:
- to: meta_router_v2_address (the address is also returned in the api).
- value: native_amount (in case swapping from native, otherwise 0).
- data: encoded_data (from build api)

The API supports 2 different methods, so it may return either:
- swap(SwapExecutionParams calldata execution)
- swapSimpleMode(IAggregationExecutor caller, SwapDescriptionV2 memory desc, bytes calldata executorData, bytes calldata clientData)

**Comment by bakeiro** [comment]
ok, thanks for the info!
